[mgr]
prepend_keymap = [
    { on = [ "g", "l" ], run = """ shell 'for f in "$@"; do new_name=$(echo "${f##*/}" | tr "[:upper:]" "[:lower:]"); mv -v "$f" "${f%/*}/$new_name"; done' --confirm """, desc = "Lowercase" },
    { on = [ "g", "s" ], run = """ shell 'for f in "$@"; do new_name=$(echo "${f##*/}" | sed "s/ /_/g"); mv -v "$f" "${f%/*}/$new_name"; done' --confirm """, desc = "Snake_case" },
    { on = [ "g", "S" ], run = """ shell 'for f in "$@"; do dir="${f%/*}"; name="${f##*/}"; new_name=$(echo "$name" | tr "[:upper:]" "[:lower:]" | sed "s/ /_/g"); if [ "$name" != "$new_name" ]; then mv -f "$f" "$dir/$new_name"; fi; done' --confirm """, desc = "Super Clean (low_snake)" },
    { on = [ "g", "z" ], run = 'shell "zip -r archived_$(date +%F).zip %s" --confirm', desc = "Zip selection" },
    { on = [ "g", "g" ], run = 'shell "lazygit" --block', desc = "Lazygit" },
    { on = [ "s", "f" ], run = 'shell "rg -i --hidden --glob \"!.git/*\" \"$(read -p \"Search: \" val && echo $val)\" | less"', desc = "Search inside files" },
    { on = [ "m", "s" ], run = "linemode size", desc = "Show sizes" },
]
